### ISSUE TITLE
Add David Chambers to Clojurebridge Board

### ISSUE THREAD

**Issue by mookerji** [ClojureBridge/board#1]
- [x] Google Calendar for meeting
- [x] README.md of this repository
- [x] clojurebridge github account
- [x] google groups
- [x] trello board
- [x] LastPass account

For @davidchambers. 

/cc @yokolet

**Comment by yokolet** [comment]
I added David as the same email address as the one subscribed to board member ml. @davidchambers if you prefer other email address for google calendar, let me know.

**Comment by yokolet** [comment]
I just changed David's github account as owner of ClojureBridge.

**Comment by davidchambers** [comment]
We're so close! Is there anything I can do to help us check that last box? :)

**Comment by yokolet** [comment]
@davidchambers do you have Trello account? and want to use the same email for ClojureBridge Trello? If so, write it to board member ml which is private. If not, I'll send the invitation to your email on board member ml.

**Comment by davidchambers** [comment]
I don't think I have a Trello account, so I'd appreciate an invitation. :)

**Comment by yokolet** [comment]
OK. I sent Trello invitation. Check your email box.

**Comment by davidchambers** [comment]
Thanks! I think this issue can now be closed.

**Comment by yokolet** [comment]
No problem. I see you on the Trello member list. So, I'm going to close this issue.
Welcome aboard, @davidchambers !!

**Comment by davidchambers** [comment]
Thanks!

**Comment by davidchambers** [comment]
I appear not to be able to comment on Trello posts. Admittedly I've never used Trello before, but I'd expect to see a comment field at the bottom of each post. Am I missing something?

**Comment by yokolet** [comment]
Hmm,,, as far as I look at members list, @davidrchambers is there and user status is the same as others. Are you looking at https://trello.com/b/OUg7YXl2/clojurebridge-core-meeting-agendas ?

**Comment by davidchambers** [comment]
> Are you looking at https://trello.com/b/OUg7YXl2/clojurebridge-core-meeting-agendas ?

Yes, I am. I can view the posts, so I certainly have read access.

Could you post a screenshot of the UI for commenting, just to make sure I'm looking in the right place?
