### ISSUE TITLE
Meeting 2018/01/25 ?

### ISSUE THREAD

**Issue by crkoehnen** [ClojureBridge/board#17]
If there's nothing on the agenda, should we cancel?

I had a couple of updates/questions but those could be handled by issues.  (I'll open.)

**Comment by davidchambers** [comment]
> If there's nothing on the agenda, should we cancel?

Let's meet anyway. If we only have a few things to discuss it will be a short meeting. :)

> I had a couple of updates/questions but those could be handled by issues. (I'll open.)

I will also open one issue for a proposal I'd like to discuss during the meeting.

**Comment by crkoehnen** [comment]
See you this afternoon!
