### ISSUE TITLE
Clojurebridge.org is down

### ISSUE THREAD

**Issue by aspasia** [ClojureBridge/board#21]
Not sure if this is the right place but thought to give it a try

**Comment by davidchambers** [comment]
Thanks for letting us know, @aspasia! Hopefully if we restart the application all will be well. @yokolet, could you run whichever `heroku` command restarts the application? :crossed_fingers:

**Comment by davidchambers** [comment]
@jgkite, are you able to grant @vsmart, @crkoehnen, and me access to the Heroku application?

**Comment by jgkite** [comment]
@davidchambers I added the email you have on your GitHub profile as a collaborator on the Heroku side. I'd need emails for the other two since they're not public in GitHub (or now that you're a collaborator you should be able to grant them access).

**Comment by davidchambers** [comment]
Thank you, Jamie! I'll invite Franka and Chris. :)

**Comment by vsmart** [comment]
Thanks @jgkite ! I was able to look into the error. Error code was: 'free dyno quota exceeded'. 

According to the docs, 

> When you reach 100% of your account quota .... your application’s dynos will be put to sleep for the remainder of that month. As a result, any apps using free dynos will not be accessible for the remainder of the month. 

So tomorrow is April 1, it should recover automatically. Leaving this open until then. 
We might consider upgrading to the basic tier to avoid this in the future, though that comes at a 7$/month fee.

**Comment by davidchambers** [comment]
Thanks for investigating this, Franka!

Let's switch to the Jekyll site before this problem arises again. :)

**Comment by davidchambers** [comment]
The site is back up, so I'll close this issue. I commit to resolving the underlying issue this month.
