### ISSUE TITLE
Add Malwine to ClojureBridge Board

### ISSUE THREAD

**Issue by yokolet** [ClojureBridge/board#4]
Tasks for @Malwine

/cc @zahara 
- [x] Google Calendar invite for meeting
- [x] README.md of this repository
- [x] clojurebridge github account role
- [ ] google groups' roles
- [x] trello board
- [ ] LastPass account

**Comment by davidchambers** [comment]
Welcome, @Malwine!

**Comment by Malwine** [comment]
Hello everybody! I am excited to join. 

Moreover, I'd like to introduce you to my ClojureBridge Berlin co-organizer Arne @plexus. He would like to join the next meeting to share our insights from the last two workshops. If that's ok we would call the team together via Hangouts (or any other service) from Berlin.

**Comment by yokolet** [comment]
@Malwine welcome!
It's nice to have @plexus to our next meeting. Berlin team looks doing really awesome. The board meeting is scheduled on Monday February 29, 3:00-4:00pm EST. It will be 9:00-10:00pm in Berlin time. I got @Malwine 's email from Ali, so I'll write you to have @plexus 's email. GH needs email to invite.

BTW, daylight saving time starts March 13 this year. Our meeting will be moved up an hour in your time. This is because our meeting is adjusted to lunch time in Pacific zone.

**Comment by Malwine** [comment]
@yokolet Thank you. Just replied.

**Comment by plexus** [comment]
Hi everyone, thanks for inviting me to Monday's meeting. I'm currently traveling in New Zealand, but I'll do my best to join.

**Comment by yokolet** [comment]
@plexus you may join us in March. I'll invite you for Monday's meeting, but feel free to skip it.

**Comment by yokolet** [comment]
@Malwine I invited your gmail to board ml. mailbox.org address is better for you?

**Comment by Malwine** [comment]
for the mailing list the mailbox.org might be better :blush:

**Comment by Malwine** [comment]
It would be great to be added at trello with mailbox.org so I can access all my boards at the same time. Thank you.

**Comment by yokolet** [comment]
@Malwine ok. I'll send another invites for you with mailbox.org address.

**Comment by Malwine** [comment]
@yokolet Thank you! :cat:

**Comment by yokolet** [comment]
Done. Check, you can see https://trello.com/b/OUg7YXl2/clojurebridge-core-meeting-agendas 
Also, accept board ml invitation.

**Comment by yokolet** [comment]
@Malwine what about LastPass? mailbox account is good for it?

**Comment by Malwine** [comment]
@yokolet I am sorry I missed this comment. I am not sure. My primary mail is mailbox.org but if it is in any way connected to Google I'll use the google account. E.g. the google calendar etc.
