### ISSUE TITLE
Add @crkoehnen to the ClojureBridge Board

### ISSUE THREAD

**Issue by mookerji** [ClojureBridge/board#5]
Tasks for @crkoehnen

/cc @annapawlicka @yokolet  
- [x] Google Calendar invite for meeting
- [x] README.md of this repository
- [?] clojurebridge github account role
- [ ] google groups' roles
- [x] trello board
- [x] LastPass account

**Comment by yokolet** [comment]
Current status as of Aug 12.
- Google Calendar invite: done
- README update: done
- github account: Buro has invited, awaiting to be accepted
- Google groups
  - board: Yoko sent an invitation, awaiting to be accepted
  - Workshops: changed status to owner
- Trello: guess done
- LastPass: done
