### ISSUE TITLE
invite Franka to ClojureBridge team on Trello

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/board#7]
I'm assigning this to you, Yoko, as I don't seem to have permission to add team members. Perhaps you could make me an administrator while you're at it. :)

See my email message from earlier this week for Franka's email address.

**Comment by yokolet** [comment]
@davidchambers Have you logged in with ClojureBridge credential? The password is shared by LastPass. But, it looks @vsmart doesn't have trello account.

@vsmart would you create an account at Trello?

**Comment by vsmart** [comment]
@yokolet I have a trello account but under a different email adress. I'll send it to you via email.

**Comment by vsmart** [comment]
Got into trello 🎉 Closing this.
