### ISSUE TITLE
invite Franka to ClojureBridge Workshops mailing list

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/board#8]
I'm assigning this to you, Yoko, as I don't have permission to invite people. Perhaps you could make me an owner while you're at it. :)

See my email message from earlier this week for Franka's email address.

**Comment by davidchambers** [comment]
Do you have permission to perform this action, @crkoehnen?

**Comment by davidchambers** [comment]
((:bell:)) @crkoehnen

**Comment by crkoehnen** [comment]
I do, I think.

@vsmart, let me know if you don't get an invite.

**Comment by davidchambers** [comment]
Thanks, Chris. :)
