### ISSUE TITLE
invite Franka to ClojureBridge team on LastPass

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/board#9]
I'm assigning this to you, Yoko, as I've lost my master password! I'm sorry for all the bother.

See my email message from earlier this week for Franka's email address.

**Comment by yokolet** [comment]
Sure.

I emailed @vsmart. Once I get her email, I will add.

**Comment by vsmart** [comment]
Hi! I joined the team on lastpass and it seems to have worked (it says "enterprise account") but I can't yet see any sites in there. 🤔 Do you know if there are any other steps? Or maybe it just takes a while to sync?

**Comment by yokolet** [comment]
@vsmart I just shared the folder with you. Unless users accept invitation and is listed on the group, sharing folder is not available. Would you check again? I think you can see the shared folder.

**Comment by vsmart** [comment]
Yep, all works 👍 👯
